### ISSUE TITLE
something about svfa

### ISSUE THREAD

**Issue by mengjianwei12345** [rbonifacio/svfa-scala#16]
Hello, if I want to ask what is the difference between these branches, if I want to use the SVFA features in my project, which branch should I use?

**Comment by mengjianwei12345** [comment]
In addition, when I use the master branch of the project, the project will report an error:
Exception in thread "main" java.lang.NoClassDefFoundError: scala/collection/IterableOnce
at br.unb.cic.soot.graph.Graph.<init>(Graph.scala:142)
at br.unb.cic.soot.svfa.SVFA.<init>(SVFA.scala:24)
at br.unb.cic.soot.svfa.jimple.JSVFA.<init>(JSVFA.scala:28)
at br.unb.cic.analysis.svfa.SVFAAnalysis.<init>(SVFAAnalysis.java:22)
at br.unb.cic.analysis.Main.runSparseValueFlowAnalysis(Main.java:198)
But if I upgrade the scala version to 2.13.x, it will report an error:
Exception in thread "main" java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce
at br.unb.cic.analysis.Main.runSparseValueFlowAnalysis(Main.java:198)
at br.unb.cic.analysis.Main.main(Main.java:61)
